spring:
  application:
    name: user-center
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://xxxxxxxxxxxxxx/user_center?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC'
    username: root
    password: xxxxxxxxxxxx
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  redis:
    port: 6379
    host: xxxxxxx
    database: 0
    password: xxxxxxxxx
server:
  address: 0.0.0.0
  servlet:
    context-path: /api
    session:
      cookie:
        domain: kallinchen.cn
