spring:
  application:
    name: user-center
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://user.kallinchen.cn:3306/user_center?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC'
    username: root
    password: Cyx990924+-408
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  redis:
    port: 6379
    host: user.kallinchen.cn
    database: 0
    password: 19990924
server:
  address: 0.0.0.0
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
